### ISSUE TITLE
Release non-java 0.2.2.pre.1

### ISSUE THREAD

**Issue by deivid-rodriguez** [ruby/io-wait#12]
Current there's 0.2.2.pre.1 that includes java support, but there's no corresponding 0.2.2.pre.1 version that can be installed outside of JRuby? So, since the previous 0.2.1 version has the opposite issue (works outside of JRuby, but not on JRuby), it's no possible to use any version that works with both.

Could 0.2.2.pre.1 (non java) be released, or alternatively java and non java variants of a new 0.2.2 version?

Thanks!

**Comment by hsbt** [comment]
@headius Can you push `0.2.2.pre.1` tag into GitHub?

**Comment by headius** [comment]
The preview release was pushed for testing purposes and because I am not comfortable pushing a full release without buying from the other maintainers. I'd be happy to push a tag for the preview today but perhaps we should discuss getting a proper 0.2.2 release out.

**Comment by headius** [comment]
I pushed a commit updating the gemspec version and tagged it as v0.2.2.pre1.

**Comment by deivid-rodriguez** [comment]
I was actually aiming for a rubygems.org release, but it's fine. In any case, io-wait might be moved right into core: https://bugs.ruby-lang.org/issues/18566. So this gem will get emptied eventually, right?

**Comment by headius** [comment]
It does appear that will happen, but 3.1 will still be using the default gem and JRuby 9.4 will target 3.1 so we will follow suit.

I'm not sure what the migration path is going forward, since an empty gem would break Ruby 3.1 users (the gem will be activated and may interfere with the shipped default gem).

**Comment by deivid-rodriguez** [comment]
> It does appear that will happen, but 3.1 will still be using the default gem and JRuby 9.4 will target 3.1 so we will follow suit.

Yep, makes sense.

> I'm not sure what the migration path is going forward, since an empty gem would break Ruby 3.1 users (the gem will be activated and may interfere with the shipped default gem).

If guess this empty gem won't support 3.1, it will have `required_ruby_version >= 3.2`?

**Comment by headius** [comment]
> If guess this empty gem won't support 3.1, it will have required_ruby_version >= 3.2?

Yeah that is probably an option. I assume RubyGems won't attempt to install such a gem on an earlier version, so 3.1 should be protected from the null gem?

**Comment by headius** [comment]
Note however that the suggestion of moving io-wait back into core was proposed in part because TruffleRuby does not support the gem at all, and it also does not currently support 3.2, so this fix would not help them. It is a rather messy situation.

**Comment by deivid-rodriguez** [comment]
Yes, it's quite messy 🤣.

> Yeah that is probably an option. I assume RubyGems won't attempt to install such a gem on an earlier version, so 3.1 should be protected from the null gem?

Yes! Well, some old versions of Bundler & RubyGems may _attempt_ to install this gem due to resolution bugs, but the install will fail due to the compatibility issue. So I think this empty gem should sneak into older rubies.

**Comment by eregon** [comment]
Could we do something like FFI, where the gem just require the stdlib instead?
https://github.com/ffi/ffi/blob/447845cb3030194c79700c86fb388a12e6f81386/lib/ffi.rb#L19-L26
I'd try this in `lib/io/wait.rb`:
```ruby
  $LOAD_PATH.delete(File.expand_path('../..', __FILE__))
  require 'io/wait'
```

I think this will be needed anyway for several default gems which should really just delegate to the stdlib/core on TruffleRuby and possibly on old CRuby versions as well, and any other Ruby implementation.

**Comment by headius** [comment]
I believe that code in the ffi gem is a relic from when JRuby shipped its own copy of the Ruby sources. Now we use the Ruby sources from the gem with our internal extension, as in the code a few lines above.

I am very reluctant to muck around with the load path in this way but I don't have a better suggestion at the moment.

**Comment by hsbt** [comment]
@deivid-rodriguez I released 0.2.2.pre1 with ruby platform.

**Comment by deivid-rodriguez** [comment]
Awesome, thanks!

**Comment by eregon** [comment]
> I am very reluctant to muck around with the load path in this way but I don't have a better suggestion at the moment.

I can't think of any other way that would work on existing Rubies.
We could add some `require_stdlib` method or so, but it wouldn't help existing releases.
Using `gem_original_require` would also not work as long as the gem is in `$LOAD_PATH`.
I think removing the gem from `$LOAD_PATH` is not too bad as the gem is actually delegating to stdlib and should be ignored after this initial step.

(Another idea would be to use RbConfig or so to try to find the stdlib directory/ies and do an absolute require. This wouldn't work for existing truffleruby releases, because there are multiple stdlib directories (lib/mri, lib/truffle), and only one is in RbConfig. It would also break if such a file would do a non-absolute require and seems brittle)

**Comment by eregon** [comment]
Actually, the gem could just be empty and have no files, no?
Then `require 'io/wait'` would just require the stdlib, which has been there forever.
